[project]
name = "backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Lizbeth", email = "lizbeth.espinosa@udea.edu.co"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "persistence-kit @ git+https://github.com/AndresFSerrano/persistence-kit.git",
    "boto3 (>=1.43.24,<2.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"